In [1]:
import numpy as np

In [8]:
board = [
    [7,8,0,4,0,0,1,2,0],
    [6,0,0,0,7,5,0,0,9],
    [0,0,0,6,0,1,0,7,8],
    [0,0,7,0,4,0,2,6,0],
    [0,0,1,0,5,0,9,3,0],
    [9,0,4,0,6,0,0,0,5],
    [0,7,0,3,0,0,0,1,2],
    [1,2,0,0,0,7,4,0,0],
    [0,4,9,2,0,6,0,0,7]
]

In [3]:
def possible(row,column,board,value):
    for x  in range(0,9):
        if board[row][x] == value or board[x][column] == value:
            return False
    
    row = (row//3)*3
    column = (column//3)*3
    for i in range(row,row+3):
        for j in range(column,column+3):
            if board[i][j] == value:
                return False
    return True

In [9]:
def solve():
    for x in range(9):
        for y in range(9):
            if board[x][y] == 0:
                for z in range(1,10):
                    if possible(x,y,board,z):
                        board[x][y] = z
                        solve()
                        board[x][y] = 0
                return
    
    print(np.matrix(board))

In [12]:
solve()

[[7 8 5 4 3 9 1 2 6]
 [6 1 2 8 7 5 3 4 9]
 [4 9 3 6 2 1 5 7 8]
 [8 5 7 9 4 3 2 6 1]
 [2 6 1 7 5 8 9 3 4]
 [9 3 4 1 6 2 7 8 5]
 [5 7 8 3 9 4 6 1 2]
 [1 2 6 5 8 7 4 9 3]
 [3 4 9 2 1 6 8 5 7]]
